import type { Appointment } from '@/types';

export const data: Appointment[] = [
  {
    id: 1,
    barberId: '1',
    client: 'James Wilson',
    service: 'Fade & Beard',
    date: '24',
    time: '10:00 AM',
    duration: 2,
    status: 'Confirmed',
    price: 45,
    color: 'bg-primary/20 border-primary/50 text-primary-foreground',
  },
  {
    id: 2,
    barberId: '2',
    client: 'Elena R.',
    service: 'Kids Cut',
    date: '24',
    time: '02:00 PM',
    duration: 1,
    status: 'Confirmed',
    price: 30,
    color: 'bg-blue-500/20 border-blue-500/50 text-blue-100',
  },
  {
    id: 3,
    barberId: '1',
    client: 'Robert Brown',
    service: 'Royal Shave',
    date: '24',
    time: '04:00 PM',
    duration: 1,
    status: 'Pending',
    price: 55,
    color: 'bg-purple-500/20 border-purple-500/50 text-purple-100',
  },
  {
    id: 4,
    barberId: '3',
    client: 'Mike K.',
    service: 'Buzz Cut',
    date: '24',
    time: '09:00 AM',
    duration: 1,
    status: 'Completed',
    price: 25,
    color: 'bg-green-500/20 border-green-500/50 text-green-100',
  },
  {
    id: 5,
    barberId: '1',
    client: 'Sarah M.',
    service: 'Coloring',
    date: '25',
    time: '11:00 AM',
    duration: 2,
    status: 'Confirmed',
    price: 120,
    color: 'bg-orange-500/20 border-orange-500/50 text-orange-100',
  },
  {
    id: 6,
    barberId: '2',
    client: 'David L.',
    service: 'Haircut',
    date: '26',
    time: '01:00 PM',
    duration: 1,
    status: 'Confirmed',
    price: 40,
    color: 'bg-blue-500/20 border-blue-500/50 text-blue-100',
  },
];
