export const clients = [
  {
    id: 1,
    name: 'James Wilson',
    email: 'j.wilson@example.com',
    phone: '+1 (555) 012-3456',
    avatar: 'https://picsum.photos/seed/james/100',
    lastVisit: 'Oct 24, 2023',
    totalSpend: 1250,
    visits: 12,
    status: 'VIP',
  },
  {
    id: 2,
    name: 'Elena Rodriguez',
    email: 'elena.r@example.com',
    phone: '+1 (555) 098-7654',
    avatar: 'https://picsum.photos/seed/elena/100',
    lastVisit: 'Oct 20, 2023',
    totalSpend: 450,
    visits: 4,
    status: 'Regular',
  },
  {
    id: 3,
    name: 'Robert Brown',
    email: 'r.brown@example.com',
    phone: '+1 (555) 111-2222',
    avatar: 'https://picsum.photos/seed/robert/100',
    lastVisit: 'Oct 15, 2023',
    totalSpend: 890,
    visits: 8,
    status: 'Returning',
  },
  {
    id: 4,
    name: 'Sarah Miller',
    email: 'sarah.m@example.com',
    phone: '+1 (555) 333-4444',
    avatar: 'https://picsum.photos/seed/sarah/100',
    lastVisit: 'Sep 30, 2023',
    totalSpend: 2100,
    visits: 18,
    status: 'VIP',
  },
  {
    id: 5,
    name: 'Michael Chen',
    email: 'm.chen@example.com',
    phone: '+1 (555) 555-6666',
    avatar: 'https://picsum.photos/seed/michael/100',
    lastVisit: 'Oct 25, 2023',
    totalSpend: 120,
    visits: 2,
    status: 'New',
  },
];